# Generated by Django 2.1.2 on 2018-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('key', models.CharField(max_length=32)),
                ('iv', models.CharField(default=b'\xaf\xda\x8a\xd5\xf6\x9bk\xa0,\xe5\xbf\x18\xc7\xe5A\xe1', max_length=16)),
                ('mode', models.CharField(choices=[('cbc', 'CBC'), ('ctr', 'CTR'), ('ofb', 'OFB'), ('cfb', 'CFB'), ('cfb8', 'CFB8'), ('gcm', 'GCM')], max_length=4)),
                ('encrypted_message', models.CharField(max_length=2048)),
            ],
        ),
    ]
