# Generated by Django 2.1.2 on 2018-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='iv',
            field=models.CharField(default=b'DX\x88\x89\xe0I\xbe\xe8p\xfe\xb5\xb7\x12\xa5\xcb.', max_length=128),
        ),
    ]
