# Generated by Django 2.1.2 on 2018-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20181020_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decryption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_message', models.CharField(max_length=2048)),
                ('key', models.CharField(max_length=32)),
                ('iv', models.CharField(max_length=128)),
                ('mode', models.CharField(choices=[('cbc', 'CBC'), ('ctr', 'CTR'), ('ofb', 'OFB'), ('cfb', 'CFB'), ('cfb8', 'CFB8'), ('gcm', 'GCM')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='encryption',
            name='iv',
            field=models.CharField(default=b'\x0b\x8b\xdf9SvMd\x91qbn\r\x94\xd7Z', max_length=128),
        ),
    ]
