# Generated by Django 2.1.2 on 2018-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20181020_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryption',
            name='decrypted_message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='encrypted_message',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='iv',
            field=models.CharField(default=b'\rn_q\xd5!\x9a\x1b*V\xdc\x92\r\xcb\xd7\xb6', max_length=128),
        ),
    ]
